### ISSUE TITLE
Update System.Threading.Channels

### ISSUE THREAD

**Issue by dittodhole** [Open-NET-Libraries/Open.ChannelExtensions#14]
Hi there,

could you possibly update the reference to [`System.Threading.Channels`](https://www.nuget.org/packages/System.Threading.Channels/) to `5.0.0`?

**Comment by electricessence** [comment]
Sure, lemme see what I can do.

**Comment by electricessence** [comment]
DONE.
https://www.nuget.org/packages/Open.ChannelExtensions/5.0.0
