### ISSUE TITLE
IntelliSense not showing in VisualStudio

### ISSUE THREAD

**Issue by BobSilent** [Open-NET-Libraries/Open.ChannelExtensions#19]
IntelliSense does not show up in VisualStudio (VS2022)
![image](https://user-images.githubusercontent.com/13506173/163029983-84e3d8d4-8e03-492b-b87e-7af7ceacd30f.png)

When renaming `Documentation.xml` to `Open.ChannelExtensions.xml`
in `C:\Users\<account>\.nuget\packages\open.channelextensions\6.0.1\lib\netstandard2.1`
it shows up
![image](https://user-images.githubusercontent.com/13506173/163030171-b4f29209-4ab3-4cb3-a665-d6fabf6be0f8.png)

**Comment by electricessence** [comment]
Ok will fix ASAP!.  I ran into this recently with other projects.  Thanks for pointing this out.

**Comment by electricessence** [comment]
Updated.  Please get the latest and check again and let me know. :)  (I tested it.  Should work now.)
https://www.nuget.org/packages/Open.ChannelExtensions/6.0.2

**Comment by BobSilent** [comment]
perfect, thanks for the fast fix (as i said i had the workaround 😉)

And you really miss this tiny little help information, which is really essential 😄

And thanks for this really really great extension!!

**Comment by electricessence** [comment]
Glad to be of service!  And I'm with you!  I love that stuff.  Been getting my docs game on lock. ;)
