### ISSUE TITLE
BatchingChannelReader Timer ObjectDisposedException

### ISSUE THREAD

**Issue by Lukazoid** [Open-NET-Libraries/Open.ChannelExtensions#20]
Today I encountered the following exception:
```
System.ObjectDisposedException: Cannot access a disposed object.
   at System.Threading.TimerQueueTimer.Change(UInt32 dueTime, UInt32 period)
   at System.Threading.Timer.Change(Int64 dueTime, Int64 period)
   at Open.ChannelExtensions.BatchingChannelReader`1.TryPipeItems(Boolean flush)
   at Open.ChannelExtensions.BufferingChannelReader`2.TryRead(TOut& item)
```
I think this can occur because it's possible `TryPipeItems` retrieves the _timer value on thread A, the last item is pushed to the channel on thread B which disposes and nulls _timer, but then TryPipeItems on thread A still tries to use the value it previously loaded which has now been disposed.

**Comment by electricessence** [comment]
Investigating.

**Comment by electricessence** [comment]
I believe you are correct about the possibility.  I'm attempting a fix.
Will be published shortly.

**Comment by electricessence** [comment]
v6.0.3 released to nuget
https://www.nuget.org/packages/Open.ChannelExtensions/6.0.3

THANK YOU!!!
