### ISSUE TITLE
Proper way to signal to all that there is no more?

### ISSUE THREAD

**Issue by adamhathcock** [Open-NET-Libraries/Open.ChannelExtensions#46]
I have a setup similar to this (not real):
```
channel
      .Reader.Batch(100)
      .WithTimeout(HTTP_BATCH_TIMEOUT)
      .PipeAsync(
        MAX_PARALLELISM_HTTP,
        async x => await Phase2(),
        -1,
        false,
        cancellationToken
      )
      .Join()
      .Batch(10 )
      .WithTimeout(HTTP_BATCH_TIMEOUT)
      .ReadAllConcurrently(MAX_CACHE_WRITE_PARALLELISM, Phase3(), cancellationToken);
```

 I write to the `channel` when needed but I also want to signal I'm done to shut everything down and move on.    I've done it by `channel.Writer.Complete();`
 
 This shuts down the channel but other channels are still listening and processing when shutting down to move on.  The task returned by the chain above completes.  I decided to make a dummy message and look for it to the last phase3 to trigger the complete but that's not great.
 
 Is there a better way to handle this?  What am I missing?

**Comment by electricessence** [comment]
Sorry for the late reply.  I'll look into this tomorrow.
BTW, love seeing these complex scenarios, especially in practice.
So are you saying that the "piped" channel is not registering that there's no more coming?
Lemme get back to you.
Can you write a unit test that would demonstrate that the expected behavior is failing?

**Comment by electricessence** [comment]
I added the following test and it works as expected.  Thoughts?

https://github.com/Open-NET-Libraries/Open.ChannelExtensions/blob/master/Open.ChannelExtensions.Tests/BatchTests.cs#L414

```cs
	[Fact]
	public static async Task AnotherComplexBatchJoinScenario()
	{
		const int SIZE = 300000;
		const long HTTP_BATCH_TIMEOUT = 10000;
		const int MAX_PARALLELISM_HTTP = 8;
		const int MAX_CACHE_WRITE_PARALLELISM = 8;

		using var cts = new CancellationTokenSource(30_000);
		var cancellationToken = cts.Token;
		var channel = Channel.CreateBounded<int>(new BoundedChannelOptions(20) { SingleReader = false, SingleWriter = true });

		int remaining = SIZE;
		_ = Task.Run(async () =>
		{
			int n = 50;

			while(remaining > 0)
			{
				await Task.Delay(20);
				for (int i = 0; remaining > 0 && i < n; i++)
				{
					await channel.Writer.WriteAsync(remaining, cancellationToken);
					remaining--;
				}

				n += 15;
			}

			await Task.Delay(30);
			channel.Writer.Complete();
		});

		int count = 0;
		var total = await channel.Reader
			.Batch(100)
			.WithTimeout(HTTP_BATCH_TIMEOUT)
			.PipeAsync(
				MAX_PARALLELISM_HTTP,
				async x =>
				{
					await Task.Delay(50);
					return x.ConvertAll(x => x * 2);
				},
				cancellationToken: cancellationToken
			)
			.Join()
			.Batch(10)
			.WithTimeout(HTTP_BATCH_TIMEOUT)
			.ReadAllConcurrently(
				MAX_CACHE_WRITE_PARALLELISM,
				x =>
				{
					Debug.WriteLine("Value: {0}", string.Join(' ', x));
					for (int i = 0; i < x.Count; i++)
						Interlocked.Increment(ref count);
				},
				cancellationToken);

		remaining.Should().Be(0);
		channel.Reader.TryRead(out _).Should().BeFalse();
		count.Should().Be(SIZE);
	}
```

**Comment by electricessence** [comment]
> This shuts down the channel but other channels are still listening and processing when shutting down to move on.

I think this is where I'm confused.  What other channels?

**Comment by adamhathcock** [comment]
> So are you saying that the "piped" channel is not registering that there's no more coming?

I think the problem is that the Pipe and ReadConcurrent channels are still active (e.g. have stuff to process) when the first channel is complete.  I'd like to complete the items but only the first to move on when everything is done.

I thought I saw this situation (stuff left to process in the downstream) while calling complete on the initial channel and exceptions being thrown on the other channels.

**Comment by adamhathcock** [comment]
> I think this is where I'm confused. What other channels?

When I say "other channels" I guess I'm referring to ones made in the background from `Pipe` and `ReadAllConcurrently` but I don't know how things work!

I'm just trying to see if I have a misunderstanding how things should be or not.

It looked like some extensions had an overload with `complete` that might be I need or maybe not.

**Comment by electricessence** [comment]
So when using `.Pipe` or `.PipeAsync`, the channel that is created there is essentially a child of the reader and will respond to completion by propagating that completion downstream.  If you wanted different behavior then you wouldn't use `.Pipe` or `.PipeAsync`.  You'd could have two separate channels that you create and manage then you could use `.PipeTo` if you wanted to do something more complex.

I honestly don't see the problem as when you call `.Complete()` on the source channel, that just signals that there will be no more coming, and when the last item leaves the channel, the downstream channels will marked as complete as well and they subsequently need to finish processing.

The unit test I posted works flawlessly and as expected.   I may still not understand your concern or special case you are trying to manage.  Are you trying to abandon items in the pipeline and cancel after completion?

**Comment by adamhathcock** [comment]
> Are you trying to abandon items in the pipeline and cancel after completion?

After asking you and reading up further, I will retest and look at this.  I could be just running into something else or mistaken all together.

I don't think I'm doing anything special and it should just work.  Thanks a lot for your time!

**Comment by electricessence** [comment]
K.  Closing for now. :)
