### ISSUE TITLE
GetBatchSize does equals instead of equals or greater

### ISSUE THREAD

**Issue by adamhathcock** [Open-NET-Libraries/Open.ChannelExtensions#47]
I made a custom BatchingChannelReader which uses a size instead of collection count.  This works fine but the internal logic is equals instead of greater or equals.  I think it should be `>=`

**Comment by electricessence** [comment]
Why are you doing this?  You see the `Debug.Assert` on the line above?
When would it ever be greater than the `full` amount?
It makes no sense to check `>=` when you know it can't be greater.

**Comment by adamhathcock** [comment]
What I'm doing is subclassing the BatchingChannelReader myself and adding in a new facility to batch by size of the payload rather than the number.  This means it will be greater than the stated capacity at points.  I've "fixed" this myself but I thought it it would be useful to batch when it is greater.

If this goes beyond the intent then no worries.

**Comment by electricessence** [comment]
Size of the payload?  I'm still very confused.
Maybe a batching channel reader isn't what you need?
I can tell you that the change you made would make no difference in the behavior.

**Comment by adamhathcock** [comment]
Each item in the channel is something I'm going to upload.  I want to batch them up to a certain size.  I get the size of each item and figure out a batch to upload.

It makes a difference when the capacity is based on size of each item and the items are variable size.

No worries about merging though.  Just don't seal the `BatchingChannelReader` :)

**Comment by electricessence** [comment]
Yeah, I don't think what you're trying to do is going to work with with this API.

**Comment by electricessence** [comment]
Sorta related, check out the latest update:
https://github.com/Open-NET-Libraries/Open.ChannelExtensions/pull/49
Better performance through batch pooling. (optional)

**Comment by electricessence** [comment]
Better performance through batch pooling.

**Comment by adamhathcock** [comment]
I think what you did is orthogonal to what I'm doing.  I still think judging the batch by item size instead of by count is valid though I understand if you don't want it in this lib.

I will take a look at the pooling though!

**Comment by electricessence** [comment]
When you have a working sample, I'm curious to see.
